name: Server CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Install only non-dev dependencies
        run: npm install --production
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: 'cards-test-api'
          if: github.ref == 'refs/heads/master' && job.status == 'success'
          run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
